{
  "user_info": {
    "username": "PhironNova",
    "password": "00110022Aa",
    "username": "PhironNova",
    "password": "00110022Aa",
    "username": "885338",
    "password": "d16fYN",
    "username": "296933",
    "password": "Yw132Q",
    "username": "723015",
    "password": "VfGrmD",
    "username": "454399",
    "password": "1usfXJ",
    "username": "178415",
    "password": "u9P3A1",
    "username": "553262",
    "password": "dX1Vz8",
    "username": "877763",
    "password": "Tc656z",
    "username": "328323",
    "password": "bQRVpk",
    "message": null,
    "auth": 1,
    "status": "Active",
    "exp_date":  null,
    "is_trial": "0",
    "active_cons": 0,
    "max_connections": "100",
    "allowed_output_formats": [
      "m3u8",
      "ts",
      "rtmp"
    ]
  },
  "server_info": {
    "xui": true,
    "version": "1.5.5",
    "revision": 2,
    "url": "aplausos123.com",
    "url": "aplausos123.com",
    "url": "aplausos123.com",
    "url": "aplausos123.com",
    "url": "aplausos123.com",
    "url": "aplausos123.com",
    "url": "aplausos123.com",
    "url": "aplausos123.com",
    "url": "aplausos123.com",
    "url": "aplausos123.com",
    "port": "80",
    "https_port": "443",
    "server_protocol": "http",
    "rtmp_port": "8880",
    "timestamp_now": 1774892165,
    "timezone": "America/Sao_Paulo"
  }
}